
- name: Debug ns_name
  ansible.builtin.debug:
    var: ns_name

- name: Debug service
  ansible.builtin.debug:
    var: service

- name: Iterate process_service_entry
  vars:
    service_name: "{{ service_entry.key }}"
    path: "{{ service_entry.value }}"
  ansible.builtin.include_tasks: _3_process_service.yml
  loop: "{{ service | dict2items }}"
  loop_control:
    loop_var: service_entry