
- name: Debug secret-store
  debug:
    msg: "{{ ss_state }} {{ ss_namespace }} {{ ss_name }} {{ ss_access_zone }} {{ server }} {{ _ca_provider }} {{ _auth }}"

- name: "Update store {{ resource_namespace }}/{{ resource_name }} ({{ ss_access_zone }})"
  kubernetes.core.k8s:
    state: "{{ ss_state }}"
    apply: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: "{{ ss_access_zone }}"
      metadata:
        name: "{{ ss_name }}"
        namespace: "{{ ss_namespace }}"
      spec:
        retrySettings:
          retryInterval: "60s"
        provider:
          vault:
            server: "{{ server }}"
            version: "v2"
            namespace: "{{ ss_namespace }}"
            caProvider: "{{ _ca_provider }}"
            auth: "{{ _auth }}"