name: Build and Release Ansible Collection

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[Vv][0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COLLECTION_PATH: ./k8s-toolkit
    container:
      image: docker.io/cytopia/ansible:latest-tools

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Ansible Collection
        id: build_collection
        run: |
          mkdir -p packages
          ansible-galaxy collection build "$COLLECTION_PATH" --output-path packages
          FILE=$(ls packages/*.tar.gz | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Debug output variable
        run: |
          echo "Built file: ${{ steps.build_collection.outputs.file }}
             
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-collection
          path: packages/*.tar.gz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

      - name: Upload package to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build_collection.outputs.file }}
          asset_name: $(basename ${{ steps.build_collection.outputs.file }})
          asset_content_type: application/gzip